# Generated by Django 2.2.6 on 2019-10-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalLevel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('trashMixed', models.IntegerField()),
                ('trashRecycled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalLevel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locallevel1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.LocalLevel1')),
            ],
        ),
        migrations.CreateModel(
            name='LocalLevel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locallevel2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.LocalLevel2')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trashCount', models.IntegerField()),
                ('mix', models.IntegerField()),
                ('paper', models.IntegerField()),
                ('plastic', models.IntegerField()),
                ('can', models.IntegerField()),
                ('locallevel3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.LocalLevel3')),
            ],
        ),
    ]
