# Generated by Django 2.2.6 on 2019-10-24 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('trashMixed', models.IntegerField()),
                ('trashRecycled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Level1')),
            ],
        ),
        migrations.CreateModel(
            name='Level3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Level2')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trashCount', models.IntegerField()),
                ('mix', models.IntegerField()),
                ('paper', models.IntegerField()),
                ('plastic', models.IntegerField()),
                ('can', models.IntegerField()),
                ('isFullPaper', models.BooleanField(default=False)),
                ('isFullCan', models.BooleanField(default=False)),
                ('isFullPlastic', models.BooleanField(default=False)),
                ('isFullMix', models.BooleanField(default=False)),
                ('level3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Level3')),
            ],
        ),
    ]
