# Generated by Django 2.2.6 on 2019-10-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('trashMixed', models.IntegerField()),
                ('trashRecycled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialSi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('trashMixed', models.IntegerField()),
                ('trashRecycled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Si',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Do')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trashCount', models.IntegerField()),
                ('mix', models.IntegerField()),
                ('paper', models.IntegerField()),
                ('plastic', models.IntegerField()),
                ('can', models.IntegerField()),
                ('dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Dong')),
            ],
        ),
        migrations.CreateModel(
            name='Gu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('si', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local.Si')),
                ('specialsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local.SpecialSi')),
            ],
        ),
        migrations.AddField(
            model_name='dong',
            name='gu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Gu'),
        ),
    ]
