# Generated by Django 2.2.6 on 2019-10-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='isFullCan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='isFullMix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='isFullPaper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='isFullPlastic',
            field=models.BooleanField(default=False),
        ),
    ]
